# Generated by Django 2.1.3 on 2020-02-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='citizenship_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='country_visited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Country'),
        ),
        migrations.AlterField(
            model_name='member',
            name='disability_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.DisabilityCard'),
        ),
        migrations.AlterField(
            model_name='member',
            name='disability_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.DisabilityType'),
        ),
        migrations.AlterField(
            model_name='member',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.EducationLevel'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foreign_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.ForeignReason'),
        ),
        migrations.AlterField(
            model_name='member',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_guardian', to='app.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.MaritalStatus'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_spouse', to='app.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='technical_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TechnicalSkill'),
        ),
        migrations.AlterField(
            model_name='member',
            name='vaccine_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.VaccineName'),
        ),
    ]
