# Generated by Django 2.1.3 on 2020-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200217_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housedetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
