# Generated by Django 2.1.3 on 2020-02-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200217_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdfacility',
            name='facility',
        ),
    ]
