# Generated by Django 2.1.3 on 2020-02-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_householdfacility_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='disease_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
