# Generated by Django 2.1.3 on 2020-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_member_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='has_technical_training',
            field=models.IntegerField(default=0),
        ),
    ]
