# Generated by Django 2.1.3 on 2020-02-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200220_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='has_disability',
            field=models.IntegerField(default=True),
        ),
    ]
