# Generated by Django 2.1.3 on 2020-02-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200220_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='has_disability',
            field=models.IntegerField(default=0),
        ),
    ]
