# Generated by Django 2.1.3 on 2020-02-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200220_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_vaccinated',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
