# Generated by Django 2.1.3 on 2020-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200220_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_child_marriage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
