# Generated by Django 2.1.3 on 2020-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200220_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='has_chronic_disease',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='has_disability',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='has_technical_training',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
