# Generated by Django 2.1.3 on 2020-02-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200220_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='monthly_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
