# Generated by Django 2.1.3 on 2020-02-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200223_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='step',
        ),
    ]
